# SUGGESTED FOLDER SETUP
# /PX4-Autopilot
#    - xrce.Dockerfile
#    - qgc.Dockerfile
#    - docker-compose.yaml
#    - joystick.Dockerfile
networks:
  emp-network:

services:
  simulation:
    image: px4io/px4-dev-ros2-foxy:latest
    container_name: px4
    tty: true
    volumes:
      - ./:/src/PX4-Autopilot/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    privileged: true
    environment:
      - DISPLAY=:0
    ports:
      - "5353:5353"
    #command: ["/bin/bash", "-c", "/src/PX4-Autopilot/px4.sh"]
  gzweb:
    build:
      context: .
      dockerfile: gzweb.Dockerfile
    container_name: gzweb
    tty: true
    environment:
      - "GAZEBO_MASTER_URI=http://simulation:11345"
    volumes:
      - ../gzweb:/src/gzweb
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./Tools/simulation/gazebo-classic/sitl_gazebo-classic/models:/gzweb/http/client/assets/
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass JEANPAUL
    volumes:
      - ./data:/data
#  uxrce:
#    build:
#      context: .
#      dockerfile: xrce.Dockerfile
#    image: ubuntu-xrcedds-suite
#    container_name: uxrcedds
#    tty: true

#  qgc:
#    build:
#      context: .
#      dockerfile: qgc.Dockerfile
#    container_name: qgroundcontrol
#    environment:
#      - DISPLAY=:0
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix:ro
#    privileged: true
#    tty: true
#    networks:
#      - emp-network

